version: '3.8'
services:
  haiwel_users_db:
    image: postgres
    container_name: users_database
    environment:
      POSTGRES_DB: "haiwel_users"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
      POSTGRES_ROOT_PASSWORD: "password"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d haiwel_users -U postgres"]
      interval: 2s
      timeout: 5s
      retries: 20
    ports:
      - "5432:5432"
    volumes:
      - haiwel_users_db:/var/lib/postgres

  user_service:
    container_name: user_service
    build:
      dockerfile: ./Dockerfile
      context: .
    image: abeldlp/haiwel_user_service
    env_file:
      - ./.env
    volumes:
      - ./:/app
    ports:
      - "8080:8080"
    depends_on:
      haiwel_users_db:
        condition: service_healthy
volumes:
  haiwel_users_db:
    driver: local
